name: Deploy to local server
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cd

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.LOCAL_SERVER }}

      - name: Set env vars
        run: echo "SSH_TARGET=100.112.150.5" >> $GITHUB_ENV

      - name: Rsync files to Linode server
        run: |
          rsync -azhv --no-t -e "ssh -o StrictHostKeyChecking=no" ./php/ deploy@${{ env.SSH_TARGET }}:/var/www/apps/itam/php/
